---
- hosts: servers
  vars:
  - data: Test_Docker
  tasks:
   - name: Copying a file from one directory to another
     shell: cp /home/agoel/mva_validation.pl /tmp/
     become: true
     become_user: root
     register: output
   - debug: msg={{output.stdout_lines}}
     with_items:
      - "{{ output }}"
   - name: Copying a file from one directory to other with variable in path
     command: cp /home/agoel/{{data}}/manifest.json /home/agoel/test
     become: yes
   - name: Copying file from one directory to another with different unknown variables in path
     command: cp /home/agoel/{{item}}/manifest.json /home/agoel/test
     with_items:
      - abcd
      - xyz
     become: yes
      
  remote_user: agoel
 
